from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime, timezone


class Provenance(BaseModel):
    """Data provenance metadata grounding computed metrics in actual source data."""
    source: str = Field(..., description="Data provider or indexer source (e.g. 'Binance Spot API', 'Solana On-chain Indexer')")
    query_timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    data_timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    methodology: str = Field(..., description="Mathematical or statistical method used for the metric")
    input_range: str = Field("24h", description="Time window or sample range analyzed")
    confidence: float = Field(1.0, ge=0.0, le=1.0)
    provider: str = Field("BinanceDataEngine")


class Citation(BaseModel):
    """Citation linking conclusions to actual retrieved data."""
    id: str
    title: str
    source: str
    detail: str
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class ActionProposal(BaseModel):
    """Safe actionable proposal generated by the agent requiring user confirmation."""
    action_type: str = Field(..., description="'TRADE', 'WATCHLIST_ADD', 'DEEP_DIVE', 'SET_ALERT'")
    title: str
    description: str
    requires_confirmation: bool = True
    payload: Dict[str, Any] = Field(default_factory=dict)
    preview_token: Optional[str] = None
